### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long in3.IN3.init()

### ISSUE THREAD

**Issue by ligi** [tincubeth/android#5]
got this via pre-launch report:

```
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: org.walleth, PID: 10775
java.lang.UnsatisfiedLinkError: No implementation found for long in3.IN3.init() (tried Java_in3_IN3_init and Java_in3_IN3_init__)
	at in3.IN3.init(Native Method)
	at in3.IN3.<init>(IN3.kt:131)
	at in3.IN3.<init>(IN3.kt:6)
	at org.walleth.activities.IN3Transport$in3$2.invoke(TincubETHActivity.kt:23)
	at org.walleth.activities.IN3Transport$in3$2.invoke(TincubETHActivity.kt:22)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.walleth.activities.IN3Transport.getIn3(Unknown Source:7)
	at org.walleth.activities.IN3Transport.setChain-B0vcT2Q(TincubETHActivity.kt:26)
	at org.walleth.activities.TincubETHActivityKt$findTincubethChains$2.invokeSuspend(TincubETHActivity.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

will try to see if ReLinker helps: https://github.com/KeepSafe/ReLinker

cc @simon-jentzsch

**Comment by ligi** [comment]
Unfortunately ReLinker did not solve the problem
